app:
  image: linkflows
  ports:
    - "8081:8081"
db:
  image: linkflows-virtuoso
  environment:
    SPARQL_UPDATE: "true"
    DEFAULT_GRAPH: "http://www.example.com/my-graph"
    DBA_PASSWORD: "admin"
  ports:
    - "8890:8890"
